export const TRANSACTION_DATA_REQUEST = 'TRANSACTION_DATA_REQUEST';
export const TRANSACTION_DATA_SUCCESS = 'TRANSACTION_DATA_SUCCESS';
export const TRANSACTION_DATA_FAILED = 'TRANSACTION_DATA_FAILED';
