import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
  mainView: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  accountValue: {
    color: '#1FAD9E',
    fontSize: 13,
    fontWeight: '600',
    marginTop: '3%',
    textAlign: 'center',
  },
  totalAccountValue: {
    color: 'green',
    fontSize: 25,
    fontWeight: 'bold',
    marginTop: '3%',
    textAlign: 'center',
  },
  totalGainView: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: '3%',
    width: Dimensions.get('window').width / 1.5,
    alignSelf: 'center',
  },
  totalGain: {
    color: 'green',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  totalGainValue: {
    color: 'green',
    fontSize: 13,
    fontWeight: '600',
  },
  portfolioView: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: '5%',
    width: Dimensions.get('window').width - 25,
    alignSelf: 'center',
  },
  textModerately: {
    color: '#1FAD9E',
    fontSize: 15,
    fontWeight: '600',
    marginTop: '1%',
    textAlign: 'center',
  },
  portfolioIndicatorView: {
    width: '70%',
    height: 20,
    backgroundColor: '#1FAD9E',
    marginTop: '3%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  portfolioIndicatorText: {fontSize: 12, color: '#FFF', fontWeight: '600'},
  divider: {
    width: Dimensions.get('window').width - 70,
    alignSelf: 'center',
    borderWidth: 0.3,
    borderColor: '#808080',
    marginTop: '5%',
  },
  recurringView: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  monthlyText: {
    color: '#000',
    fontSize: 13,
    fontWeight: '500',
  },
  settingsView: {
    width: Dimensions.get('window').width / 1.8,
    alignSelf: 'flex-start',
    height: 20,
    backgroundColor: '#1FAD9E',
    marginTop: '3%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginStart: '8%',
  },
  settingsText: {fontSize: 12, color: '#FFF', fontWeight: '600'},
  stockListView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '3%',
    width: Dimensions.get('window').width - 70,
    alignSelf: 'center',
  },
  contributionText: {
    fontSize: 15,
    color: '#000',
    fontWeight: 'bold',
    marginTop: '2%',
    marginStart: '9%',
  },
  stockName: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  stockPrice: {
    color: '#000',
    fontSize: 13,
    fontWeight: '500',
  },
  seeMore: {
    width: Dimensions.get('window').width / 1.8,
    alignSelf: 'flex-start',
    height: 20,
    backgroundColor: '#1FAD9E',
    marginTop: '3%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginStart: '8%',
  },
  seeMoreText: {fontSize: 12, color: '#FFF', fontWeight: '600'},
});
